# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_api(object):
    def setupUi(self, Dialog_api):
        Dialog_api.setObjectName("Dialog_api")
        Dialog_api.resize(849, 452)
        self.tableView_information = QtWidgets.QTableView(Dialog_api)
        self.tableView_information.setGeometry(QtCore.QRect(10, 190, 831, 241))
        self.tableView_information.setObjectName("tableView_information")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog_api)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_clients = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_clients.setObjectName("comboBox_clients")
        self.horizontalLayout.addWidget(self.comboBox_clients)
        self.pushButton_filter = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_filter.setObjectName("pushButton_filter")
        self.horizontalLayout.addWidget(self.pushButton_filter)
        self.pushButton_show_all = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_show_all.setObjectName("pushButton_show_all")
        self.horizontalLayout.addWidget(self.pushButton_show_all)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog_api)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 80, 461, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_search_string = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_search_string.setObjectName("lineEdit_search_string")
        self.horizontalLayout_3.addWidget(self.lineEdit_search_string)
        self.pushButton_search = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_3.addWidget(self.pushButton_search)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog_api)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(520, 10, 301, 92))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_ascending = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_ascending.setObjectName("radioButton_ascending")
        self.gridLayout.addWidget(self.radioButton_ascending, 2, 1, 1, 1)
        self.radioButton_descending = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_descending.setObjectName("radioButton_descending")
        self.gridLayout.addWidget(self.radioButton_descending, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.scrollArea_field_for_sorting = QtWidgets.QScrollArea(self.gridLayoutWidget)
        self.scrollArea_field_for_sorting.setWidgetResizable(True)
        self.scrollArea_field_for_sorting.setObjectName("scrollArea_field_for_sorting")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 185, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_field_for_sorting.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea_field_for_sorting, 2, 0, 2, 1)

        self.retranslateUi(Dialog_api)
        QtCore.QMetaObject.connectSlotsByName(Dialog_api)

    def retranslateUi(self, Dialog_api):
        _translate = QtCore.QCoreApplication.translate
        Dialog_api.setWindowTitle(_translate("Dialog_api", "Dialog"))
        self.label.setText(_translate("Dialog_api", "Выберите клиента"))
        self.pushButton_filter.setText(_translate("Dialog_api", "Фильтровать"))
        self.pushButton_show_all.setText(_translate("Dialog_api", "Показать все"))
        self.label_2.setText(_translate("Dialog_api", "Введите строку поиска"))
        self.pushButton_search.setText(_translate("Dialog_api", "Найти"))
        self.radioButton_ascending.setText(_translate("Dialog_api", "По возрастанию"))
        self.radioButton_descending.setText(_translate("Dialog_api", "По убыванию"))
        self.label_3.setText(_translate("Dialog_api", "Выберите поле для сортировки"))
